import { NavLink } from 'react-router-dom';
import { LayoutDashboard, Users, GraduationCap, CalendarCheck, LifeBuoy, Sprout, TrendingUp, Wheat, FlaskConical, Landmark, Network, BrainCircuit, ShieldCheck, Rocket, FileText, Settings, X } from 'lucide-react';

interface NavItem { to: string; label: string; icon: React.ComponentType<{ size?: number | string; className?: string }>; }
const NAV_ITEMS: NavItem[] = [
  { to: '/', label: 'Command', icon: LayoutDashboard }, { to: '/students', label: 'Students', icon: Users }, { to: '/academic', label: 'Academic', icon: GraduationCap }, { to: '/attendance', label: 'Attendance', icon: CalendarCheck }, { to: '/intervention', label: 'Intervention', icon: LifeBuoy }, { to: '/seeds', label: 'Seeds', icon: Sprout }, { to: '/grow', label: 'Grow', icon: TrendingUp }, { to: '/reap', label: 'Reap', icon: Wheat }, { to: '/stem', label: 'Stem', icon: FlaskConical }, { to: '/intelligence', label: 'Intelligence', icon: BrainCircuit }, { to: '/olympus', label: 'Olympus', icon: Landmark }, { to: '/nexus', label: 'Nexus', icon: Network }, { to: '/data-health', label: 'Data Health', icon: ShieldCheck }, { to: '/production', label: 'Production', icon: Rocket }, { to: '/reports', label: 'Reports', icon: FileText }, { to: '/settings', label: 'Settings', icon: Settings },
];
interface SidebarProps { open: boolean; onClose: () => void; }
export default function Sidebar({ open, onClose }: SidebarProps) {
  return <>{open && <div className="fixed inset-0 z-40 bg-navy-950/60 backdrop-blur-sm lg:hidden" onClick={onClose} aria-hidden="true" />}<aside className={`fixed inset-y-0 left-0 z-50 flex w-64 flex-col bg-navy-950 text-slate-200 transition-transform duration-200 lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between border-b border-white/10 px-5 py-6"><div><p className="text-lg font-extrabold tracking-tight text-white">PRO<span className="text-teal-400">GENS</span></p><p className="text-[11px] uppercase tracking-widest text-gold-300/90">Progress Genesis System</p></div><button type="button" onClick={onClose} className="rounded-md p-1 text-slate-400 hover:bg-white/10 hover:text-white lg:hidden" aria-label="Close navigation"><X size={20}/></button></div><nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4">{NAV_ITEMS.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={onClose} className={({ isActive }) => `group flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${isActive ? 'bg-teal-600/20 text-white ring-1 ring-inset ring-teal-500/40' : 'text-slate-300 hover:bg-white/5 hover:text-white'}`}>{({ isActive }) => <><Icon size={18} className={isActive ? 'text-teal-400' : 'text-slate-400 group-hover:text-teal-400'} /><span className="text-[13px] uppercase tracking-wide">{label}</span></>}</NavLink>)}</nav><div className="border-t border-white/10 px-5 py-4"><p className="text-[11px] leading-relaxed text-slate-400">Potential <span className="text-teal-400">→</span> Progress <span className="text-teal-400">→</span> Excellence</p></div></aside></>;
}
