import { Wheat, Target, AlertTriangle, Award } from 'lucide-react';
import StatusBadge from '../components/ui/StatusBadge';
import { usePhase5 } from '../hooks/usePhase5';

export default function Reap() {
  const { data, loading, error } = usePhase5();
  if (loading) return <p className="text-sm text-slate-500">Loading REAP from live data...</p>;
  if (error || !data) return <p className="text-sm text-rose-600">Unable to load REAP: {error ?? 'No data.'}</p>;
  const rows = data.students.filter((r) => r.reap).sort((a, b) => priorityRank(a.reap?.priority) - priorityRank(b.reap?.priority) || (a.reap?.spmReadiness ?? 0) - (b.reap?.spmReadiness ?? 0));
  const elite = rows.filter((r) => (r.reap?.spmReadiness ?? 0) >= 90).slice(0, 6);
  const p1 = rows.filter((r) => r.reap?.priority === 'P1');
  const assessed = data.reap.assessed;

  return <div className="space-y-6">
    <div className="card flex items-start gap-4 p-5"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-navy-900 text-gold-300"><Wheat size={22} /></div><div><h2 className="text-base font-extrabold text-navy-950">REAP — Results Excellence & Achievement Programme</h2><p className="mt-1 text-sm text-slate-500">Live Tingkatan 5 readiness command layer. SPM Readiness is a transparent academic proxy, not an official GPS prediction.</p></div></div>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-5"><Metric icon={Target} label="T5 Students" value={data.reap.total} /><Metric icon={Target} label="Assessed" value={assessed} /><Metric icon={Award} label="Average Index" value={data.reap.average ? data.reap.average.toFixed(1) : '—'} /><Metric icon={AlertTriangle} label="P1" value={data.reap.p1} /><Metric icon={Award} label="High Readiness" value={elite.length} /></section>
    <div className="card p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-bold uppercase tracking-wide text-navy-900">REAP Priority Queue</h3><p className="text-xs text-slate-500">P1 = Critical/High risk; P2 = Moderate or significant absence signal; P3 = lower immediate risk.</p></div><span className="text-xs font-semibold text-slate-500">{rows.length} students</span></div><div className="space-y-3">{rows.map((r) => <div key={r.student.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold">{r.student.name}</p><p className="text-xs text-slate-500">{r.student.className} · Current {r.reap?.current.toFixed(1)} · Gap {r.reap?.gap.toFixed(1)}</p></div><div className="flex items-center gap-2"><StatusBadge status={r.reap?.risk ?? 'Unassessed'} /><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-navy-800">{r.reap?.priority}</span></div></div><div className="mt-3 grid gap-3 md:grid-cols-3"><div><p className="text-[11px] font-semibold uppercase text-slate-400">SPM readiness proxy</p><p className="text-sm font-bold">{r.reap?.spmReadiness.toFixed(1)} / 100</p></div><div><p className="text-[11px] font-semibold uppercase text-slate-400">Absence signal</p><p className="text-sm">{r.absentDays > 0 ? `${r.absentDays} hari tidak hadir` : 'Tiada rekod ketidakhadiran dalam sumber'}</p></div><div><p className="text-[11px] font-semibold uppercase text-slate-400">Intervention</p><p className="text-xs text-slate-600">{r.reap?.intervention}</p></div></div></div>)}</div></div>
    <div className="card p-5"><h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-navy-900">Elite / Sustain</h3>{elite.length ? <div className="grid gap-2 md:grid-cols-2">{elite.map((r) => <div key={r.student.id} className="rounded-lg border border-slate-200 p-3"><p className="text-sm font-semibold">{r.student.name}</p><p className="text-xs text-slate-500">{r.student.className} · readiness {r.reap?.spmReadiness.toFixed(1)}</p></div>)}</div> : <p className="text-sm text-slate-500">No students currently reach the ≥90 readiness proxy threshold.</p>}</div>
    {p1.length > 0 && <div className="rounded-lg border border-rose-200 bg-rose-50 p-4"><p className="text-sm font-bold text-rose-800">Action required: {p1.length} P1 students</p><p className="mt-1 text-xs text-rose-700">Assign or review intervention coverage before the next assessment cycle.</p></div>}
  </div>;
}
function priorityRank(value?: string) { return value === 'P1' ? 1 : value === 'P2' ? 2 : 3; }
function Metric({ icon: Icon, label, value }: { icon: typeof Target; label: string; value: number | string }) { return <div className="card p-4"><div className="flex items-center gap-2 text-slate-500"><Icon size={15} /><span className="text-xs font-semibold">{label}</span></div><p className="mt-1 text-2xl font-extrabold text-navy-950">{value}</p></div>; }
